# Lints and tests code

name: Python tests

# Run when pushing or pull_requesting on develop and master
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        python -m pytest -s  --junitxml=junit/test-results.xml --cov=otri --cov-report=xml --cov-report=html

    - name: Upload coverage result artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-cov-report
        path: htmlcov
